# Generated by Django 4.2.10 on 2024-04-01 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('styles', '0002_alter_style_options'),
        ('organizators', '0003_alter_teacherstyle_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность в минутах')),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('shooting', models.CharField(max_length=255)),
                ('music', models.CharField(max_length=255)),
                ('age_restrictions', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='data_images/')),
                ('master_class', models.BooleanField()),
                ('count_people', models.IntegerField()),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styles.style')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizators.teacher')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
