# Generated by Django 4.2.10 on 2024-03-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizators', '0002_alter_company_options_alter_organizator_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherstyle',
            options={'verbose_name': 'Стиль преподавателя', 'verbose_name_plural': 'Стили преподавателя'},
        ),
    ]
