# Generated by Django 4.2.10 on 2024-04-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizators', '0003_alter_teacherstyle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.FileField(null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
