# Generated by Django 4.2.10 on 2024-04-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizators', '0004_teacher_address_teacher_image_teacher_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
