# Generated by Django 4.2.10 on 2024-04-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0002_alter_style_options'),
        ('organizators', '0005_alter_company_rating_alter_teacher_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizators.company')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styles.style')),
            ],
            options={
                'verbose_name': 'Стиль преподавателя в шкоел',
                'verbose_name_plural': 'Стили преподавателя в школах',
            },
        ),
    ]
