# Generated by Django 4.2.10 on 2024-05-12 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizators', '0006_companystyle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companystyle',
            options={'verbose_name': 'Стиль преподавателя в школе', 'verbose_name_plural': 'Стили преподавателя в школах'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='schedule',
            field=models.CharField(max_length=255, null=True, verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='company',
            name='schedule',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CompanyTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizators.company')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizators.teacher')),
            ],
            options={
                'verbose_name': 'Учитель в школе',
                'verbose_name_plural': 'Учителя в школе',
            },
        ),
    ]
