# Generated by Django 4.2.10 on 2024-05-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizators', '0007_alter_companystyle_options_teacher_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='teachers',
            field=models.ManyToManyField(related_name='groups', through='organizators.CompanyTeacher', to='organizators.teacher'),
        ),
    ]
