# Generated by Django 4.2.10 on 2024-05-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizators', '0009_remove_teacher_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='photo',
            new_name='image',
        ),
    ]
