# Generated by Django 4.2.10 on 2024-03-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='style',
            options={'verbose_name': 'Стиль', 'verbose_name_plural': 'Стили'},
        ),
    ]
