# Generated by Django 4.2.10 on 2024-03-04 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('count_people', models.IntegerField()),
                ('price', models.CharField(max_length=255)),
                ('present', models.CharField(max_length=255)),
                ('conditions', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='event_images/')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styles.style')),
            ],
        ),
    ]
