# Generated by Django 4.2.10 on 2024-04-01 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizators', '0006_companystyle'),
        ('events', '0003_alter_event_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizatorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('organizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizators.organizator')),
            ],
            options={
                'verbose_name': 'Мероприятие организатора',
                'verbose_name_plural': 'Мероприятия организаторов',
            },
        ),
    ]
