# Generated by Django 4.2.10 on 2024-05-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_organizatorevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(max_length=255, verbose_name='Длительность мероприятия'),
        ),
    ]
