# Generated by Django 4.2.10 on 2024-05-12 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizators', '0007_alter_companystyle_options_teacher_description_and_more'),
        ('user', '0003_alter_user_birthdate_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizators.organizator'),
        ),
    ]
